sudo: required
services:
    - docker
env:
    global:
        - TAG=0.1
        - secure: 't9dYXQ7SEysi+jlOx5Ibg6NTAfy3AMiCek6aGUbyfuCLyVX8wa1FOLLiLfoBfpa8e+TMUq4IDZNeBHqefsamXnHG8rM6+LMdmoeQpx0lbHDa3TvMr2yB/b5fGI3h+sOA40nu+C72epWv3CpJQQlGm6rnyVZQi+9ea08TONKe/NoWHRVMdKO7q7ZHnfTF6lEQvYjocyWQrllnDNOn0/ekR7GzgIp0OrepGYYutUi9NixSUslvG1MQcT4F/+fs9tXj2N2UxP6PkNq3pGvuELaqa4/4A76O49QsNFPiskwRrIQ9LTASSO9l4KTzaFiIO7LheQKEQP9yX48/CqtBLkCTi9igp1WRSCyPdynjJF1ZPssIZHMuJp4nzB+yJtKLbJBzEAQqDy82spsnZIPDvVbCqejmMNXsURiyGgUsNV7yf42sbO0Vqc8ujCQLQ7G2DEqpO9NY1CCuSY9LaMmc2IvXZlTz3mge3xK8+8TlAMfYSGMZTTLfuJyW666Q987gT24kMRCW48PjnQ3lxrtvU6CxAn+csmDjeBC586n7bUbojoenZmTkbpCjEd3HuScactnov7mb1gD5YVUYxKnqtIxVgnTT3Igh/RWaqhn13sx+StwhBITjAiPjHRHEBgi0qLlzqe5XWVwMc+wCfmwhVUaj3oIrWQuQmI3Ft/oxAyc4MqIE='
        - secure: 'IVSjO7saUWsWLjJaLCxVET2l3ufB2s4SqCv5XnykMs4xdZiNbZFXHX/jGijT+DMjFrQgWqOPiuU+CnxOrMv4C9Bc8rsWJwfoy7NDJrgKgVGFg9Lq0oOMYtsydbJhIJoDpkq16Vlr8skyoMUIfIp7gY+WCOuIqJmN9zRDpps6tYet61QNs3Zx9/3xYqlaHIUetKEyaiL1SL2RWVQHM/O7oKLCPbVuv2AcSin1AOQH69ac5bC3oZxecGbvpgyNhRjKSpwCVcMK0WibDSqbiy+NEkqjg/Y7VclwE6V4kwFaQbcsLkvTI6gPjAQn4CGvKCuZ3Pjgc5DivLt00c5wrQZEftqdo/W2CIl6tIf2AYZ4bP5QKp2VjjAQqcLQceZb6/EJG5r4C2SaxKRNszf9e4ngF77FPnsx9028tWCHnnLf+bepNAnhjFO6xArKYhvucKyrIAGnZ8JM9eEO/sxfIIqqP9ezOo4F8jDpoNwc5B+RRL+WT5g4Nsig8Ro6aWbFnL7GzFcgv8RdnlwZSXQlNMvdQkU47fR7nWbzGtodKSd1vbvNzObR8EGQ7iiua/hASAJPWtaSK7SHh9uugwpnYNnSuCIu/uVDF79wlj0rCqMZtbQDAyE3C5ZEgnUO7fPg8d8sWgy3/DVlEHJEJ+JR9tH0U0LWSjcLSraSDDUw/fMkZVQ='
    matrix:
        - VERSION=14.04
        - VERSION=16.04
        - VERSION=18.04
script:
    - docker build -t jonathanhs/dev-vim:$TAG-ub$VERSION --build-arg VERSION=$VERSION .
after_success:
    - docker images
before_deploy:
    - echo "$DOCKER_KEY" | docker login -u "$DOCKER_ID" --password-stdin
deploy:
    provider: script
    script: docker push jonathanhs/dev-vim:$TAG-ub$VERSION
    on:
        branch: master
