sudo: required
services:
    - docker
env:
    global:
        - TAG=0.1
        - secure: "Ap2\/nLmnljIs7h5rWaNYHPj3d\+cDcwNBAkHYK8nwXRTNzA5hYKZ0IbnU5l5dBYa69sYSHx23oa\+0difVtapCBdj93W22u5358cyfnldQ1ckhdpm2nFpZOH8kqXUftGVAOfxD5Yr4xvdjMteHSZNCNo4\/YaaEVhUp\+uiHF9LMpINNigpq0j4jL7O0bmPnoLSd\/FQ0lWEo3wRX1yOKofPaXRHSIgYZs8oYc7qcQCRWG0YnGIYuUV\+I3IVWgTXp7rm53OldQKM5H0ju5pV3dPVl7XRyzb\/oeLrQu3oJEbem6bRz2Ty8zk698JWR7CWaCYwmVM\/7lyLNDD2l7CfJV76xXxk26CRR9fl\/aTqvfdwZEleBK\+Z5hN0PnG9BzvnvO25akj1Qywj70XeF8apGBB7scUB9\/sJG09NbJ0Piu6PjUmDpm2xc23gdzOuS7DHRXxoqb3G8iJbfikJqJFh7c50mqxF\+jrxjrWsOSZjbZeRW0r9n2HypXcQZGiAeIdUX2x0NQsL8j2ExMsQ\/oPg\+PQ6lQYQgnthK2NB\/V\+pG1Uqwoy7teTHPxu3tKVpIdkXlIjZ298mvPv9KixDh\+nXLEpkN3\/8lCERfa8E8PXyUTgGsuTrbmn8ZKKKaNw0PSLSQJJMPvomMBIcE\/3CYweYqaz56bcOSUKpc\/GO\/3JiprBur6oE\="
        - secure: "WsfuNeqeUOYHGP\+NvopxreJ4M3IRRQPZwLSEF3zEvXXP8fq7s1vUD9JaXwk9FF46ui16W3ys62nO\+GiK4qagh\/d\+MNljRHSsx3xL4iU\/5d1ik3tqxaIUyzH0tV47P8xZF5x1zi62\+8U6jnpJUca3q985n1pr\/8x3ktJYSxBB4ZnNmykBHNgMygZrMsKc7MdythhJxD1H7ZrDINsndiU405ZLO0N0vKfT6hoji5RhooEAJ0v42Y\/NjwXl1N8Jpgb8qsMp\+DeqBGSWUe8dTncIKRMDRGeoxJscYl4Vq\+5cVzjcgOefZyJu1rQd8q3r2n0JhqyI\/SeWr0JyZZlcMTmzHLKz7gXTpas0NxNo3U\+hSHL19gwFYqMiddskdwVJLJrDpIrF0ngwfgQT7TzwTqMk6rH0MMHgUpgz1wxea3p2atJTK4\+\/kGe0X9g\/yYNAQM0N5epYpNjqgrfTO2MHGCL7SZvJZzsPZqLh94deDnQzOmpjHJcb\+K0BnZWhjuYNASqFnXs6Iqs0Dq1Id4EXDzitPgCEFZgzrSYWxD\/JFYJg8UbENDNmanTE\+1blCpRm9U5NkB0boxYfbq\+nYYokNCFJMgOgUWeZC2l\/Tfsk0vxDHOQVPc42\+7WFwnipg42ii4BM2Kvc5bfrw4f6M0OH3b0Luma83pF14WGpPNU9nJJR\/HQ\="
    matrix:
        - VERSION=14.04
        - VERSION=16.04
        - VERSION=18.04
script:
    - docker build -t jonathanhs/dev-vim:$TAG-ub$VERSION --build-arg VERSION=$VERSION .
after_success:
    - docker images
before_deploy:
    - echo "$DOCKER_KEY" | docker login -u "$DOCKER_ID" --password-stdin
deploy:
    provider: script
    script: docker push jonathanhs/dev-vim:$TAG-ub$VERSION
    on:
        branch: master
